# SNNTrainer Arguments
model_name: mobilenetv3_large_100
train: True
similarity_fn: cosine_similarity
train_added_layer_only: True
add_layer: True
use_logits: True
train_dataset_path: ../create_dataset/datasets/train
eval_dataset_path: ../create_dataset/datasets/eval
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 50
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
num_train_epochs: 15
optim: adamw_torch
output_dir: data/mobilenet-SNN
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to: wandb

# Model arguments
torch_dtype: null
use_peft: true

# Data training arguments
preprocessing_num_workers: 12